#Примеры ввода:
# рубль евро доллар 2 - отобразит: 2 евро в рубль и 2 доллар в евро
# рубль евро - отобразит: 1 евро в рубль
# рубль евро доллар - отобразит:1 евро в рубль и 1 доллар в рубль
# Так же возможен ввод
# РублЬ ДоЛлаР usd - Отсеет дубликаты: 1 доллар в рубль
# RuB uSd EuR
#рУблЬ БиТкОиН пожарник - валюты пожарник нет поэтому не отображаем и т.к нет количества вызывает ошибку, хотел взять по дефолту 1 (
#usd пожарник - такая же ошибка
#usd 2 - Ошибка
#рубль белорусский биткоин гривна доллар евро лайткоин эфириум рубль




#Но я не знаю ограничения в количестве ввода, и тесты не писал, так что используем в пределах разумного )

TOKEN = "Мне же не нужно сой токе указывать?"
#У ключа приблизительно 25 дней и около 930+ запросов
API_KEY = "iEUw3FELsUUeGI62HpXezbMJ"

#Честно я не знаю работают ли они все но забавы ради нельзя было упустить случай, так что радуемся )
keys={
    "белорусский": "byn",
    "биткоин": "btc",
    "гривна": "uah",
    "доллар": "usd",
    "евро": "eur",
    "лайткоин": "ltc",
    "рубль": "rub",
    "эфириум": "eth",# 8шт точно можно запрашивать )
    "adf": "adf",
    "adp": "adp",
    "aed": "aed",
    "afa": "afa",
    "afn": "afn",
    "all": "all",
    "amd": "amd",
    "ang": "ang",
    "aoa": "aoa",
    "aon": "aon",
    "ars": "ars",
    "ats": "ats",
    "aud": "aud",
    "awg": "awg",
    "azm": "azm",
    "azn": "azn",
    "bam": "bam",
    "bbd": "bbd",
    "bdt": "bdt",
    "bef": "bef",
    "bgl": "bgl",
    "bgn": "bgn",
    "bhd": "bhd",
    "bif": "bif",
    "bmd": "bmd",
    "bnd": "bnd",
    "bob": "bob",
    "brl": "brl",
    "bsd": "bsd",
    "btn": "btn",
    "bwp": "bwp",
    "byr": "byr",
    "bzd": "bzd",
    "cad": "cad",
    "cdf": "cdf",
    "cfp": "cfp",
    "chf": "chf",
    "clf": "clf",
    "clp": "clp",
    "cnh": "cnh",
    "cny": "cny",
    "cop": "cop",
    "crc": "crc",
    "csd": "csd",
    "csk": "csk",
    "cuc": "cuc",
    "cup": "cup",
    "cve": "cve",
    "cyp": "cyp",
    "czk": "czk",
    "dem": "dem",
    "djf": "djf",
    "dkk": "dkk",
    "dop": "dop",
    "dzd": "dzd",
    "ecs": "ecs",
    "eek": "eek",
    "egp": "egp",
    "ern": "ern",
    "esp": "esp",
    "etb": "etb",
    "fim": "fim",
    "fjd": "fjd",
    "fkp": "fkp",
    "frf": "frf",
    "gbp": "gbp",
    "gel": "gel",
    "ghc": "ghc",
    "ghs": "ghs",
    "gip": "gip",
    "gmd": "gmd",
    "gnf": "gnf",
    "grd": "grd",
    "gtq": "gtq",
    "gyd": "gyd",
    "hkd": "hkd",
    "hnl": "hnl",
    "hrk": "hrk",
    "htg": "htg",
    "huf": "huf",
    "idr": "idr",
    "iep": "iep",
    "ils": "ils",
    "inr": "inr",
    "iqd": "iqd",
    "irr": "irr",
    "isk": "isk",
    "itl": "itl",
    "jmd": "jmd",
    "jod": "jod",
    "jpy": "jpy",
    "kes": "kes",
    "kgs": "kgs",
    "khr": "khr",
    "kmf": "kmf",
    "kpw": "kpw",
    "krw": "krw",
    "kwd": "kwd",
    "kyd": "kyd",
    "kzt": "kzt",
    "lak": "lak",
    "lbp": "lbp",
    "lkr": "lkr",
    "lrd": "lrd",
    "lsl": "lsl",
    "ltl": "ltl",
    "luf": "luf",
    "lvl": "lvl",
    "lyd": "lyd",
    "mad": "mad",
    "mdl": "mdl",
    "mga": "mga",
    "mgf": "mgf",
    "mkd": "mkd",
    "mmk": "mmk",
    "mnt": "mnt",
    "mop": "mop",
    "mro": "mro",
    "mru": "mru",
    "mtl": "mtl",
    "mur": "mur",
    "mvr": "mvr",
    "mwk": "mwk",
    "mxn": "mxn",
    "mxp": "mxp",
    "myr": "myr",
    "mzm": "mzm",
    "mzn": "mzn",
    "nad": "nad",
    "ngn": "ngn",
    "nio": "nio",
    "nlg": "nlg",
    "nok": "nok",
    "npr": "npr",
    "nzd": "nzd",
    "omr": "omr",
    "pab": "pab",
    "pen": "pen",
    "pgk": "pgk",
    "php": "php",
    "pkr": "pkr",
    "pln": "pln",
    "plz": "plz",
    "pte": "pte",
    "pyg": "pyg",
    "qar": "qar",
    "rol": "rol",
    "ron": "ron",
    "rsd": "rsd",
    "rwf": "rwf",
    "sar": "sar",
    "sbd": "sbd",
    "scr": "scr",
    "sdd": "sdd",
    "sdg": "sdg",
    "sdp": "sdp",
    "sek": "sek",
    "sgd": "sgd",
    "shp": "shp",
    "sit": "sit",
    "skk": "skk",
    "sll": "sll",
    "sos": "sos",
    "srd": "srd",
    "srg": "srg",
    "std": "std",
    "stn": "stn",
    "svc": "svc",
    "syp": "syp",
    "szl": "szl",
    "thb": "thb",
    "tjs": "tjs",
    "tmm": "tmm",
    "tmt": "tmt",
    "tnd": "tnd",
    "top": "top",
    "trl": "trl",
    "try": "try",
    "ttd": "ttd",
    "twd": "twd",
    "tzs": "tzs",
    "ugs": "ugs",
    "ugx": "ugx",
    "uyp": "uyp",
    "uyu": "uyu",
    "uzs": "uzs",
    "veb": "veb",
    "vef": "vef",
    "ves": "ves",
    "vnd": "vnd",
    "vuv": "vuv",
    "wst": "wst",
    "xaf": "xaf",
    "xag": "xag",
    "xau": "xau",
    "xbt": "xbt",
    "xcd": "xcd",
    "xeu": "xeu",
    "xof": "xof",
    "xpd": "xpd",
    "xpf": "xpf",
    "xpt": "xpt",
    "yer": "yer",
    "yun": "yun",
    "zar": "zar",
    "zmk": "zmk",
    "zmw": "zmw",
    "zwd": "zwd",
    "zwl": "zwl"
}
# Делаем инвертацию списка для вывода
inv_keys = {value: key for key, value in keys.items()}
